import { StyleSheet } from 'react-native';
import { theme } from '@/theme';

export default StyleSheet.create({
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.m,
    paddingHorizontal: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 14,
    flex: 1,
  },
  heroImage: {
    width: '100%',
    height: 536,
    marginBottom: theme.spacing.md,
    borderRadius: 12,
    opacity: 1,
    overflow: 'hidden',
  },
  brandRow: {
    width: 82,
    height: 27,
    borderRadius: theme.radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 17,
    marginLeft: 21,
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
  },
  neuropepSvg: {
    position: 'absolute',
    left: 21,
    top: 18,
  },
  brandTitle: {
    color: theme.colors.white,
    fontSize: 18,
    lineHeight: 27,
    fontWeight: '400',
  },
  notification: {
    position: 'absolute',
    left: 75,
    top: 160,
  },
  heroTitle: {
    color: theme.colors.textSecondary,
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 27,
    textAlign: 'center',
    alignSelf: 'center',
    marginBottom: theme.spacing.md,
    width: 268,
  },
  heroSubtitle: {
    color: theme.colors.grey,
    fontSize: theme.fontSize.sm,
    lineHeight: 20,
    textAlign: 'center',
  },
  socialButton: {
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingVertical: theme.spacing.sm,
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  socialButtonShadow: {
    shadowColor: '#636363',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  socialContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  socialIconWrapper: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.xs,
  },
  socialIcon: {
    width: 22,
    height: 22,
  },
  socialLabel: {
    fontSize: theme.fontSize.md,
    color: theme.colors.textSecondary,
    fontWeight: '500',
  },
  heroLink: {
    color: theme.colors.gradientEnd,
    fontSize: theme.fontSize.sm,
    fontWeight: '500',
    textAlign: 'center',
  },
});
