import { StyleSheet } from 'react-native';
import { theme } from '@/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: theme.spacing.lg,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  brandTitle: {
    color: theme.colors.gradientEnd,
    fontSize: 24,
    fontWeight: '800',
  },
  actionGroup: {
    flexDirection: 'row',
    gap: theme.spacing.m,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  iconText: {
    fontSize: 18,
  },
  greeting: {
    color: theme.colors.text,
    fontSize: 20,
    fontWeight: '600',
    marginBottom: theme.spacing.xs,
  },
  subheading: {
    color: theme.colors.grey,
    fontSize: 15,
    marginBottom: theme.spacing.lg,
  },
  briefHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  briefLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.xs,
  },
  
  // Bottom tab navigation styling is handled in navigation layer only.
  scrollContent: {
    paddingBottom: 100,
  },
  unlockedBriefCard: {
    borderColor: '#D9D9D9',
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    backgroundColor: theme.colors.white,
    marginBottom: 20,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 30,
    elevation: 6,
  },
  unlockedBriefTitle: {
    color: theme.colors.gradientEnd,
    fontSize: 15,
    fontWeight: '600',
  },
  briefArrowTransparent: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unlockedBriefText: {
    fontSize: 15,
    color: theme.colors.textSecondary,
    lineHeight: 22,
    marginBottom: 12,
  },
  boldText: {
    fontWeight: '700',
    color: theme.colors.text,
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 4,
  },
  activeDotPill: {
    width: 24,
    height: 4,
    borderRadius: 2,
  },
  inactiveDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E0E0E0',
  },
  alertBanner: {
    backgroundColor: '#F9F1FB',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  alertHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  alertIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2D3142',
  },
  alertBody: {
    fontSize: 14,
    color: '#6C6F80',
    marginLeft: 32,
    lineHeight: 20,
  },
  dismissButton: {
    alignSelf: 'flex-end',
    marginTop: 4,
  },
  dismissText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF383C',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  sectionHeading: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
  },
  statsGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 24,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F0E5F8',
    paddingVertical: 14,
    justifyContent: 'center',
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
    paddingLeft: 8
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  blockHeading: {
    fontSize: 16,
    fontWeight: '400',
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  checklistCard: {
    backgroundColor: '#F3F3F5',
    borderRadius: 20,
    padding: 16,
    marginBottom: 24,
    gap: 12,
  },
  checklistItemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  checklistTextWrap: {
    flexDirection: 'column',
    gap: 4,
  },
  checklistTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
  },
  checklistSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  checklistSubText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  bulletSeparator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#9E7B1D',
    marginHorizontal: 2,
  },
  checklistTimeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#947005',
  },
  markDoneButton: {
    borderWidth: 1,
    borderColor: '#BD2BF2',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  markDoneText: {
    color: '#BD2BF2',
    fontSize: 13,
    fontWeight: '400',
  },
  fabContainer: {
    position: 'absolute',
    bottom: 24,
    right: 16,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  fabGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 24,
  },
  fabText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
});
