import { StyleSheet } from 'react-native';
import { theme } from '@/theme';

export default StyleSheet.create({
  content: {
    flex: 1,
    paddingHorizontal: theme.spacing.md,
  },
  headerRow: {
    marginBottom: theme.spacing.md,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  headerTitle: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '500',
    marginBottom: theme.spacing.lg,
    color: theme.colors.textSecondary,
  },
  smallLabel: {
    fontSize: 16,
    fontWeight: '500',
    marginBottom: theme.spacing.sm,
    color: theme.colors.text,
  },
  link: {
    color: theme.colors.gradientEnd,
    fontWeight: '500',
    fontSize: 15,
    textDecorationLine: 'underline',
    marginBottom: 8,
  },
  scheduleCard: {
    backgroundColor: theme.colors.inActive,
    borderRadius: 12,
    paddingLeft: theme.spacing.md,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.md,
  },
  previewRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    paddingBottom: theme.spacing.sm,
  },
  dayWrap: { alignItems: 'center', marginRight: 12, gap: 8 },
  priorityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  dashboardCard: {
    backgroundColor: theme.colors.dashboardCardBg,
    borderRadius: theme.radius.m,
    padding: theme.spacing.md,
    marginTop: theme.spacing.md,
  },
  dashboardHeader: {
    marginBottom: theme.spacing.md,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dashboardPreview: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
    marginBottom: theme.spacing.lg,
  },
  dashboardCheckboxLabel: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    fontWeight: '500',
    marginLeft: theme.spacing.xs,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionHint: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.cardSubText,
  },
  daySelected: {
    width: 56,
    height: 56,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayBox: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayLabel: { color: theme.colors.text, fontWeight: '600' },
  dayLabelSelected: { color: theme.colors.white, fontWeight: '700' },
  dayShort: { marginTop: 8, color: theme.colors.textSecondary, fontSize: 12 },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: theme.spacing.lg,
    width: '85%',
    gap: 8,
  },
  infoCard: {
    flex: 1,
    backgroundColor: theme.colors.cardBg,
    borderTopLeftRadius: theme.radius.m,
    borderTopRightRadius: theme.radius.m,
    borderBottomRightRadius: theme.radius.m,
    paddingTop: 13,
    paddingBottom: 12,
    paddingLeft: 11,
    paddingRight: 17,
  },
  infoText: {
    color: theme.colors.textSecondary,
    fontSize: theme.fontSize.md,
    lineHeight: 20,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gridSmall: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  selectionList: {
    width: '100%',
  },
  footer: {
    marginTop: 'auto',
    gap: theme.spacing.md,
  },
  subText: {
    color: theme.colors.subText,
    fontSize: 15,
    textAlign: 'center',
    paddingBottom: 8,
  },
  statusMsgCard: {
    width: '100%',
    height: 64,
    borderRadius: 12,
    backgroundColor: '#F9F1FB',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  statusText: {
    fontSize: theme.fontSize.sm,
    fontWeight: '400',
    color: theme.colors.textSecondary,
  },
  statusIcon: {
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pendingCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: '#E2D3E8',
    backgroundColor: 'transparent',
  },
});
